name: Labeller

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [assigned, unassigned, review_requested, review_request_removed]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  handle-pull-request-review:
    runs-on: ubuntu-latest
    if: github.event_name	== 'pull_request_review'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PR submitted and approved
        if: always() && github.event.review.state == 'approved'
        run: |
          prNum="${{ github.event.pull_request.number }}"
          gh pr edit $prNum --remove-label "approved,awaiting-review,changes-requested"

      - name: PR submitted and approved
        if: always() && github.event.review.state == 'approved'
        run: |
          prNum="${{ github.event.pull_request.number }}"
          gh pr edit $prNum --add-label approved

      - name: PR dismissed
        if: always() && github.event.review.state == 'dismissed'
        run: |
          prNum="${{ github.event.pull_request.number }}"
          gh pr edit $prNum --add-label awaiting-review

      - name: PR submitted and approved
        if: always() && github.event.review.state == 'changes_requested'
        run: |
          prNum="${{ github.event.pull_request.number }}"
          gh pr edit $prNum --add-label changes-requested

  handle-pull-request-review-assignment:
    runs-on: ubuntu-latest
    if: github.event_name	== 'pull_request' && (github.event.action	== 'review_request_removed' || github.event.action	== 'review_requested')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: PR assigned
        run: |
          prNum="${{ github.event.pull_request.number }}"
          gh pr edit $prNum --remove-label "assigned"

          echo ${{ toJson(github.event.pull_request) }}

          metadata='${{ toJson(github.event.pull_request.requested_reviewers) }}'
          reviewerCount=$(jq -c -n '$data | length' --argjson data "$metadata")
          if [[ $reviewerCount -gt 0 ]]
          then
            gh pr edit $prNum --add-label assigned
          fi
